name: Java CI with Maven

on:
  push:
    branches: [ "test" ] # Trigger on changes to the test branch
  pull_request:
    branches: [ "main" ] # Run checks on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the project using Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Push changes to main branch if tests pass
      - name: Push to main branch
        if: success() # Only run this step if the build is successful
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge test --no-ff -m "Merge changes from test branch after successful build"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}